[package]

name = "gen_art"
version = "0.0.1"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[dependencies.lux]
path = "../lux/"

[[bin]]
path = "./src/bin.rs"
name = "gen_art"

[dependencies]
nd_iter = "*"
rand = "*"
rustc-serialize = "*"
gif = "*"
palette = "*"
